### ISSUE TITLE
Unknown parameter "0" when using options

### ISSUE THREAD

**Issue by ChinesePeanuts** [toverux/ngsweetalert2#12]
Hi,

I'm using _ngsweetalert2_ and I'm a bit struggling.  
I would like to create a modal for a request with the `preConfirm` option (similar to the _Ajax request example_ in the official documentation)

The problem is, when I'm using :
```
<swal #dialog title="Delete?" type="warning"
   options="{showLoaderOnConfirm=true, preConfirm: onDelete(item.pId) }"></swal>
```

I am having `SweetAlert2: Unknown parameter "0"` in my console (and it goes from "0" to "74").
Even when `options={}` is empty, I'm having the error from "0" to "1"

Thanks in advance for your help

---
_Project INFO:_
_Angular: 4.2.2_

**Comment by limonte** [comment]
I'm closing this in favor of https://github.com/toverux/ngsweetalert2/issues/12

**Comment by toverux** [comment]
Hi @ChinesePeanuts,

You've just committed a small mistake: you're not binding the options attribute with an object, but you're initializing it with a string :)

Instead of `options="{ }"` it should be `[options]={}`.
That way, Angular parses it.

It works with `title` or `type` because we don't need more than simple strings, but you could also write: `[title]="'my title'"` (notice the single quotes in the double quotes).

https://angular.io/guide/template-syntax

**Comment by ChinesePeanuts** [comment]
Oh, what a silly mistake, thanks for the help !
