### ISSUE TITLE
How to implement preConfirm event in directive

### ISSUE THREAD

**Issue by yanlyan** [toverux/ngsweetalert2#18]
How to implement preConfirm event in directive ? I just found 2 event in documentation, confirm and cancel. Where to place preConfirm event ?

I have tried to add it inside options 

`[swal]="{preConfirm: preConfirm() }"`

but the preConfirm was not found 

`ERROR TypeError: params.preConfirm is not a function`

**Comment by toverux** [comment]
There's no event emitter for preConfirm (I don't want to wrap too much things for unfrequent use cases where the current implementation already permits everything).

But you seem to be almost right. I assume you have a function like this in you component?

```typescript
public preConfirm(): void {
    // ...
}
```

Then the right syntax is:

```html
<button [swal]="{ preConfirm: preConfirm }"></button>
```

Notice the removal of the parentheses. Otherwise you use the result of the call to `preConfirm` as the Swal option value.
