### ISSUE TITLE
i can not use route.navigate after then

### ISSUE THREAD

**Issue by rifkysyaripudin** [toverux/ngsweetalert2#29]
I want to move the component after the OK button is pressed.
I use code like this,

`result.subscribe((data) => {
            swal({
                title: 'Good job!',
                text: data.message,
                type: 'success',
            }).then(function () {
                this.router.navigate(['menus/categories']);
            });
        });`

But the result of a console like this,

`RROR Error: Uncaught (in promise): TypeError: Cannot read property 'router' of undefined
TypeError: Cannot read property 'router' of undefined
    at form.component.ts:94`

Is there anything wrong or can not be with route.navigate?

**Comment by toverux** [comment]
Hi @rifkysyaripudin,

You are using `swal()`, so this is not technically about **Ng**SweetAlert2, but SweetAlert2.

Anyway, that is because you're using function() in the callback of then(), and `function()` expressions in JavaScript don't capture the `this` of the scope in which the callback is defined, unlike the other variables. You need to use the arrow notation (`() =>`).

I've explained it all here, where an user has the same problem you have: https://github.com/limonte/sweetalert2/issues/630#issuecomment-331239542

**Comment by rifkysyaripudin** [comment]
Oh yeah, it work. Awesome!
Thanks @toverux
