### ISSUE TITLE
Type Error

### ISSUE THREAD

**Issue by RoshanRoyal** [toverux/ngsweetalert2#30]
Getting type exception after code running.

[at-loader] Checking finished with 2 errors
[at-loader] node_modules\sweetalert2\sweetalert2.d.ts:212:9
    TS1110: Type expected.

[at-loader] node_modules\sweetalert2\sweetalert2.d.ts:308:20
    TS1110: Type expected.

**Comment by toverux** [comment]
Hello @RoshanRoyal, thanks for reporting :) 
However, be more careful the next time, this is a SweetAlert2-specific problem. Fortunately, I'm also the author of SweetAlert's type definition file (.d.ts).

I've been able to reproduce by downgrading to TypeScript 2.0. Your TS version does not understand the syntax of lines 212 and 308, because the syntax it uses has been introduced in TypeScript 2.1.

I'll create a PR in SweetAlert2 in a few minutes to restore compatibility with TS 2.0.

**Comment by toverux** [comment]
Fixed ; please follow the PR referenced above to be noticed when a new version of SweetAlert2 is released. Alternatively, you can also upgrade your TypeScript version, it's worth it!

**Comment by RoshanRoyal** [comment]
Hi toverux,

after resolving above issue i am getting metioned error.

WARNING in ./~/@toverux/ngsweetalert2/dist/esm+types/src/di.js
2:30-44 "export 'InjectionToken' was not found in '@angular/core'

EXCEPTION: Uncaught (in promise): TypeError: __WEBPACK_IMPORTED_MODULE_0__angular_core__.InjectionToken is not a constructor
TypeError: __WEBPACK_IMPORTED_MODULE_0__angular_core__.InjectionToken is not a constructor

**Comment by toverux** [comment]
Ach... I see that I introduced an Angular 2.x-incompatible change in v2.0.0.
I'll fix it when possible.

In the meantime, you can install NgSweetAlert2 v.1.2.2 which is still compatible with Angular 2.x (and it has almost the same features as the current version, see the changelog for more info).
